### ISSUE TITLE
RuntimeError: mat1 and mat2 must have the same dtype

### ISSUE THREAD

**Issue by HarrySSH** [llava-rlhf/LLaVA-RLHF#12]
Thanks very much. that indeed solved my issue previously.  👍 
And I am sorry to raise another RuntimeError I have :)

I encountered a bug in File "/home/XXX/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 131, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype

I tried to print the input, self.weight, self.bias. with the following codes. 
It looks alright to me ... Any thoughts on what could be the issue?
        try:
                    print("input type:", input.dtype)
                    input = input.to(dtype=torch.float16)
                except:
                    pass
                try:
                    print("weight type:", self.weight.dtype)
                except:
                    pass
                try:
                    print("Bias type:", self.bias.dtype)
                except:
                    pass
                return F.linear(input, self.weight, self.bias)
input type: torch.bfloat16
weight type: torch.bfloat16
Bias type: torch.bfloat16
input type: torch.bfloat16
weight type: torch.bfloat16
Bias type: torch.bfloat16
rollout:   0%|                                            | 0/1 [00:00<?, ?it/s]
steps:   0%|                                           | 0/6004 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/finetune_lora_ppo.py", line 565, in <module>
    train()
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/finetune_lora_ppo.py", line 557, in train
    trainer.train(
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/rl_trainer.py", line 329, in train
    self.log_history.append(self.step(infinite_train_dataloader, step_idx))
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/rl_trainer.py", line 254, in step
    rollouts = self.rollout(queries_batches)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/ppo_trainer.py", line 245, in rollout
    respond_outputs = unwrapped_policy.respond(
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/rl_models.py", line 339, in respond
    return self.policy.respond(
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/rl_models.py", line 74, in respond
    self._respond(
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/rl_models.py", line 164, in _respond
    sequences = self.base_model.generate(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/peft/peft_model.py", line 977, in generate
Traceback (most recent call last):
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/finetune_lora_ppo.py", line 565, in <module>
    outputs = self.base_model.generate(**kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    train()
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/finetune_lora_ppo.py", line 557, in train
    trainer.train(
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/rl_trainer.py", line 329, in train
    return self.sample(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    self.log_history.append(self.step(infinite_train_dataloader, step_idx))
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/rl_trainer.py", line 254, in step
    rollouts = self.rollout(queries_batches)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/ppo_trainer.py", line 245, in rollout
    respond_outputs = unwrapped_policy.respond(
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/rl_models.py", line 339, in respond
    return self.policy.respond(
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/rl_models.py", line 74, in respond
    self._respond(
  File "/home/bear/Documents/harry/LLaVA-RLHF/RLHF/models/rl_models.py", line 164, in _respond
    sequences = self.base_model.generate(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/peft/peft_model.py", line 977, in generate
    outputs = self(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    outputs = self.base_model.generate(**kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/bear/Documents/harry/LLaVA/llava/model/language_model/llava_llama.py", line 75, in forward
    input_ids, attention_mask, past_key_values, inputs_embeds, labels = self.prepare_inputs_labels_for_multimodal(input_ids, attention_mask, past_key_values, labels, images)
  File "/home/bear/Documents/harry/LLaVA/llava/model/llava_arch.py", line 104, in prepare_inputs_labels_for_multimodal
    image_features = self.encode_images(images)
  File "/home/bear/Documents/harry/LLaVA/llava/model/llava_arch.py", line 84, in encode_images
    image_features = self.get_model().get_vision_tower()(images)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return self.sample(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bear/Documents/harry/LLaVA/llava/model/multimodal_encoder/clip_encoder.py", line 48, in forward
    image_forward_outs = self.vision_tower(images.to(device=self.device, dtype=self.dtype), output_hidden_states=True)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    outputs = self(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 941, in forward
    return self.vision_model(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/bear/Documents/harry/LLaVA/llava/model/language_model/llava_llama.py", line 75, in forward
    input_ids, attention_mask, past_key_values, inputs_embeds, labels = self.prepare_inputs_labels_for_multimodal(input_ids, attention_mask, past_key_values, labels, images)
  File "/home/bear/Documents/harry/LLaVA/llava/model/llava_arch.py", line 104, in prepare_inputs_labels_for_multimodal
    image_features = self.encode_images(images)
  File "/home/bear/Documents/harry/LLaVA/llava/model/llava_arch.py", line 84, in encode_images
    image_features = self.get_model().get_vision_tower()(images)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 869, in forward
    encoder_outputs = self.encoder(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bear/Documents/harry/LLaVA/llava/model/multimodal_encoder/clip_encoder.py", line 48, in forward
    image_forward_outs = self.vision_tower(images.to(device=self.device, dtype=self.dtype), output_hidden_states=True)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 655, in forward
    layer_outputs = encoder_layer(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 941, in forward
    return self.vision_model(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 385, in forward
    hidden_states, attn_weights = self.self_attn(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 869, in forward
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 274, in forward
    encoder_outputs = self.encoder(
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    query_states = self.q_proj(hidden_states) * self.scale
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 655, in forward
    return forward_call(*args, **kwargs)
  File "/home/bear/anaconda3/envs/rlhf/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 131, in forward
    return F.linear(input, self.weight, self.bias)
    RuntimeErrorlayer_outputs = encoder_layer(: 
mat1 and mat2 must have the same dtype

**Comment by Edward-Sun** [comment]
Hi,

Could you reinstall the llava package with our new patch [here](https://github.com/llava-rlhf/LLaVA-RLHF/tree/main/llava_setup)?

Also, please install `torch==2.0.1`, we found that the newest `torch==2.1.0` could lead to buggy results in its native flash-attention.

**Comment by HarrySSH** [comment]
Thank you! I will give a try!

**Comment by Amanda2024** [comment]
hi I also met this error, how did you solve it?

**Comment by Edward-Sun** [comment]
@Amanda2024 Could you reinstall the llava package with our new patch [here](https://github.com/llava-rlhf/LLaVA-RLHF/tree/main/llava_setup)?
